# 1、Goal 目标（客户端发起任务时发送）
bool enable     # 定义动作的目标，表示动作开始的指令
---

# 2、Result 最终结果 （任务完成后返回一次）
bool finish     # 定义动作的结果，表示是否成功执行
---

# 3、Feedback 实时反馈（任务运行中持续推送）
int32 state     # 定义动作的反馈，表示当前执行到的位置


# 三个顺序不能调换  三个允许任意一个为空 但2个 --- 必须保留
# 编译 .action 文件后自动生成3个类 Goal Result Feedback